apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-frontend-cfg
data:
  config.json: |-
    {
        "websocketHost": "http://iot-consumer-iotdemo.apps.ocp3.stormshift.coe.muc.redhat.com",
        "websocketPath": "/api/service-web/socket",
        "SERVER_TIMEOUT": 20000
    }
